fixtures/functions/basic-error.js, src/__snapshots__/integration.test.js.snap, src/integration.test.js, src/route.js, src/route.test.js
This PR improves the error handling of functions. I was in the situation that my function threw an error which leads to a not found route. This PR catches errors of functions and also propagates the stack trace as a response.
=> ✨ Improve functions error handling

src/commands/new.ts, src/templating/actions.ts, src/templating/data.ts, src/templating/filesystem.ts, src/utils/fs.ts
Uses the new layout of the functions-templates project to download multiple file templates into a
twilio-run project. Templates will be downloaded into the functions/{bundleName} and
assets/{bundleName} directories within the project.
This also allows for passing an empty bundleName (or filename in the twilio-run CLI parlance right
now). When empty, this adds the functions/assets directly into the functions/assets directories.
This will be used for `create-twilio-function` template options. The twilio-run CLI still enforces
a name.
BREAKING CHANGE: This needs the functions-templates repo to be up to date. Currently it points to
the next branch, which is up to date.
re #20
> All third-party contributors acknowledge that any contributions they provide will be made …
=> feat(new command): updates new to download multiple file templates

src/templating/data.ts
When downloading a template that doesn't exist the error was printed in full to the command line.
This fixes that and solves some of the issue with [create-twilio-function#19](https://github.com/twilio-labs/create-twilio-function/pull/19)
=> fix: removes console.error

README.md, src/cli.ts, src/commands/list-templates.ts, src/commands/new.ts
This will let us share the list-templates command with other projects and the CLI plugin more easily.
=> refactor: Splits list-templates command from new --list.

src/templating/actions.ts, src/templating/filesystem.ts
Namespace is a better name. This improves the output messaging as well.
=> refactor: renames "bundle" to "namespace" when downloading templates

__tests__/config/utils/credentials.test.ts, src/commands/shared.ts, src/config/utils/credentials.ts
`@twilio/core-cli` renamed the `project` flag to `profile`. Since `twilio-run` doesn't depend on `@twilio/core-cli` but does ingest its flags for some commands, we need to update here.
`project` was kept as an alternative to `profile` for now. This can likely be removed at a later date.
=> chore: change project flag to profile

src/commands/activate.ts
activate command had incorrect 'required' property which prevented treatment as a required argument when converted from yargs to oclif.
=> fix(activate): environment was 'required' not 'requiresArg'

__tests__/config/start.test.ts
Running `npm run jest` resulted in path errors under win32 systems.  This PR should address those problems found in start.test.ts.  Regression testing was done against Ubuntu to ensure tests still pass on other platforms.
=> fix(tests): win32 support for paths

__tests__/utils/debug.test.ts, src/utils/debug.ts
As described by @ShelbyZ, the redaction apparently overrides the original object. I added tests to catch that going forward and fixed the behavior by copying the original object. I think that's a fine behavior because this is only happening when debug logs are enabled. Therefore performance is less of a concern.
fix #78
=> fix(debug): fix redaction of logger overwriting values

src/runtime/route.ts, src/runtime/server.ts
It is possible to define a function that uses the Runtime prior to handler execution:
```JavaScript
const hello = require(Runtime.getFunctions()['hello'].path);
exports.handler = function(context, event, callback) {
hello.handler(context, event, () => {
console.log('ran');
callback(null, {});
});
};
```
The above code will work when deployed to Twilio, but not when hosted via twilio-run.
=> fix(server): object Runtime not available before function run

src/runtime/route.ts
- use process.hrtime() to track start/stop (supports nodeJS 8.x)
- debug log estimated execution time in milliseconds
Not sure if requiring debug() is the correct way to report this information.  We could also consider displaying a warning/error message if the estimated duration execeeds the defined limit.
Another approach to capturing timing would be to use perf_hooks to setup an observer and add measurements.  The observer could process the measurements (logging) and disconnect.
=> feat: add estimated execution time to function run

src/templating/actions.ts, src/templating/data.ts
This change surfaces the descriptive message returned when an error is encountered using GitHub API to import templates. 
Tested with status 403 rate limited exceeded and 404 page not found. Suggestions welcome.
Fixes #68 
=> feat(templates): report GitHub api error

src/commands/activate.ts
Makes `promote` the primary command, with alias `activate`.
Adds option aliases for 'activate' / 'promote' command:
* `from` = `source-environment`
* `from-build` = `build-sid`
* `to` = `environment`
Adds appropriate examples showing usage.
resolves twilio-labs/serverless-toolkit#8
=> feat(activate): change activate to alias, promote to command

__tests__/templating/filesystem.test.ts, package.json, src/templating/filesystem.ts, src/utils/fs.ts
Closes #69
this allows you to install multiple templates under the same
namepace
=> feat: allow the same namespace but different files

.github/config.yml, .gitignore, CONTRIBUTING.md, __tests__/runtime/route.test.ts, examples/basic/functions/hello.js, package.json, src/runtime/route.ts
This exposes the current function path as the PATH property on the context. This catches up with the
release of that variable in the Twilio Functions environment as introduced in
twilio.com/changelog/twilio-functions-context-path
I marked this as a breaking change because if someone used `PATH` as an env variable before this will not work anymore. 
=> feat(server): expose function path to context

src/runtime/server.ts
This changes the limit for the request body size from 100kb to 6mb which is the default for
Lambda/Twilio Functions
fix #98
=> fix(server): update request body size

src/templating/data.ts, src/types/generic.ts
Adds #90 functionality by allowing the user to circumvent rate limiting with an auth token specified in their environment.
First time contributing  to a CLI, so looking for suggestions on improvement. 🙂
=> feature: #90 allow users to specify a github token

CONTRIBUTING.md, src/checks/nodejs-version.ts
Currently, we check if the node version is 10.17. Twilio Functions cloud no longer checks minor
versions so we only need to check for 10.x
fix #111
=> fix: #111 change pinned node version to 10.x

__tests__/templating/data.test.ts, package-lock.json, package.json, src/templating/data.ts
This fixes #113. I added some basic tests for now. I'll add some additional tests before merging but I'd love your eyes at this @philnash 
=> feat(templates): add support for custom template URLs

__tests__/templating/filesystem.test.ts, src/templating/data.ts, src/templating/filesystem.ts, src/utils/fs.ts
Fixes #122
This adds a `directory` property to `TemplateFileInfo` and then uses that to place the files in the correct nested directories.
=> feat(templates): support nested templates to create nested routes

src/commands/start.ts
If the server errors with `EADDRINUSE` then we ask for a new port number with the default of the existing port number + 1.
Fixes #97.
=> feat(start): handle EADDRINUSE by asking for another port number

src/commands/new.ts, src/templating/actions.ts
`create-twilio-function` uses `downloadTemplate` from `src/templating/actions` and that would previously throw an error for a missing/nonexistant template, but it changed to catch it. Downstream functions shouldn't catch and log errors because the function consumers won't know if something went wrong.
Fixes [create-twilio-function#51](https://github.com/twilio-labs/create-twilio-function/issues/51).
=> fix(templating): catch errors in command, not before

package.json, src/commands/activate.ts, src/commands/deploy.ts, src/commands/list.ts, src/commands/logs.ts, src/utils/logger.ts
=> feat(logger): expose errors better & upgrade serverless

src/commands/start.ts, src/config/start.ts, src/printers/start.ts, src/runtime/internal/runtime-paths.ts, src/runtime/server.ts
=> feat(start): expose functions-folder and assets-folder options

package.json, src/commands/activate.ts, src/commands/deploy.ts, src/commands/list.ts, src/commands/logs.ts, src/commands/shared.ts, src/config/activate.ts, src/config/deploy.ts, src/config/list.ts, src/config/logs.ts, src/config/utils/credentials.ts
This exposes the new config values for region and edge.
re twilio-labs/serverless-toolkit#10
=> feat(flags): expose region/edge flags

__tests__/runtime/__snapshots__/integration.test.ts.snap, __tests__/runtime/integration.test.ts, fixtures/assets/hello.js, src/runtime/server.ts
Fixes #107. 
I checked and when you make an OPTIONS request to an asset you get these CORS headers:
```
access-control-allow-origin: *
access-control-allow-headers: Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
access-control-allow-methods: GET, POST, OPTIONS
access-control-expose-headers: ETag
access-control-max-age: 86400
access-control-allow-credentials: true
```
But you don't get those headers for other requests.
=> feat(runtime): add CORS headers to OPTIONS requests to assets

__tests__/config/utils/env.test.ts, package.json, src/config/activate.ts, src/config/deploy.ts, src/config/utils/env.ts
The activate command wasn't passing any environment variables to the new environment. This should fix that along with [serverless-api#49](https://github.com/twilio-labs/serverless-api/pull/49).
Fixes: #109 
=> fix(activate): prepare and pass env vars to serverless-api activateBuild

__tests__/runtime/__snapshots__/integration.test.ts.snap, __tests__/runtime/integration.test.ts, package.json, src/commands/start.ts, src/config/start.ts, src/runtime/internal/functionRunner.ts, src/runtime/internal/response.ts, src/runtime/route.ts, src/runtime/server.ts
…after callback
WIP for #135
This work replaces `functionToRoute` code that picks a function, creates the context and environment for it, runs it and responds to the express application with `functionPathToRoute` that forks a child process to do the above, killing the process once the callback is called.
Currently this works and will run and serve functions successfully in local development mode.
Current issues:
* The integration tests don't pass. As far as I can see, it is because the tests are trying to load the `functionRunner` from the TS directory and not the built JS project
* Functions are loaded fresh every time, because they are loaded into a new process. This is a breaking change and invalidates the `--live` flag (as it is always live). This is a potential performance issue.
* …
=> feat(runtime): experimental: load functions in a separate process

README.md
This adds some extra usage including conventions around private/protected functions (as #31 pointed out weren't obvious) and other bits too.
=> docs: improves the usage section of the README

.github/workflows/nodejs.yml, __tests__/config/utils/env.test.ts, package.json, src/config/utils/env.ts
=> ci: enable github actions on push
